### ISSUE TITLE
Swagger throbber image is broken

### ISSUE THREAD

**Issue by manthey** [girder/girder#446]
When you execute a task in the swagger rest api area, the 'throbber' image is supposed to appear for the duration of the execution.  The link to this image is broken (currently it points to /api/images/throbber.gif).

**Comment by manthey** [comment]
Fixed in PR #788.

**Comment by zachmullen** [comment]
@manthey I still see this error on latest master with #788 merged in

`GET http://localhost:9080/girder/api/images/throbber.gif 404 (Not Found)`

Is there something I have to do besides running `npm install` to get it working?

**Comment by manthey** [comment]
It first tries to load the throbber image from the wrong place, then the css makes it load it from the correct place.  This means that you get a 404 in the logs, but the throbber image appears to the user.

**Comment by zachmullen** [comment]
Nevermind my last comment, my server simply hadn't updated. I'm running into other issues now when I'm behind a proxy, but the throbber thing was not a real error.
